### PR TITLE
Android: Titanium 9 support

### PR DESCRIPTION
**Pull request by m1ga**
* removed local libs
* changed gradle to make it compile with cli

[ti.notificationbanner-android-2.0.0.zip](https://github.com/lambus-platform/titanium-notification-banner/files/5400413/ti.notificationbanner-android-2.0.0.zip)

### CODE REVIEW

**Comment by hansemannn** [comment]
v1.x should also work with SDK 9 already, but also being able to compile it with SDK 9 is a great improvement! Is this ready from your side @m1ga ?

**Comment by m1ga** [comment]
There was no binary and I didn't want to switch CLIs :) 

yes, done from my side. A Slack user was testing it

**Comment by hansemannn** [comment]
Thanks a lot! 🎉

**Comment by hansemannn** [comment]
Released: https://github.com/lambus-platform/titanium-notification-banner/releases/tag/android-2.0.0

**Pull request merged**
